export const CustomEmotes = [
    {
     name: '+1',
     short_names: ['+1'],
     text: '',
     emoticons: [],
     keywords: ['thumbsup'],
    },
    {
     name: 'clap',
     short_names: ['clap'],
     text: '',
     emoticons: [],
     keywords: ['clap'],
    },
    {
     name: 'mega',
     short_names: ['mega'],
     text: '',
     emoticons: [],
     keywords: ['mega','cheering megaphone'],
    },
    {
     name: 'zap',
     short_names: ['zap'],
     text: '',
     emoticons: [],
     keywords: ['zap', 'high voltage sign'],
    },
    {
     name: 'rocket',
     short_names: ['rocket'],
     text: '',
     emoticons: [],
     keywords: ['rocket'],
    },
    {
     name: 'fire',
     short_names: ['fire'],
     text: '',
     emoticons: [],
     keywords: ['fire'],
    },
    {
     name: 'hammer_and_wrench',
     short_names: ['hammer_and_wrench'],
     text: '',
     emoticons: [],
     keywords: ['hammer_and_wrench'],
    },
    {
     name: 'Smiling Face with Open Mouth and Cold Sweat',
     short_names: ['sweat_smile'],
     text: '',
     emoticons: [],
     keywords: ['Smiling Face with Open Mouth and Cold Sweat'],
    },
    {
     name: 'Rolling on the Floor Laughing',
     short_names: ['rolling_on_the_floor_laughing'],
     text: '',
     emoticons: [],
     keywords: ['Rolling on the Floor Laughing'],
    },
    {
     name: 'Face with Stuck-out Tongue and Tightly-Closed Eyes',
     short_names: ['stuck_out_tongue_closed_eyes'],
     text: '',
     emoticons: [],
     keywords: ['Face with Stuck-out Tongue and Tightly-Closed Eyes'],
    },
    {
     name: 'Grinning Face with Star Eyes',
     short_names: ["star-struck", "grinning_face_with_star_eyes"],
     text: '',
     emoticons: [],
     keywords: ['Grinning Face with Star Eyes'],
    },
    {
     name: 'Smiling Face with Smiling Eyes and Three Hearts',
     short_names: ['smiling_face_with_3_hearts'],
     text: '',
     emoticons: [],
     keywords: ['Smiling Face with Smiling Eyes and Three Hearts'],
    },
    {
     name: 'Smiling Face with Heart-Shaped Eyes',
     short_names: ['heart_eyes'],
     text: '',
     emoticons: [],
     keywords: ['Smiling Face with Heart-Shaped Eyes'],
    },
    {
     name: 'Face with Tears of Joy',
     short_names: ['joy'],
     text: '',
     emoticons: [],
     keywords: ['Face with Tears of Joy'],
    },
    {
     name: 'Disappointed but Relieved Face',
     short_names: ['disappointed_relieved'],
     text: '',
     emoticons: [],
     keywords: ['Disappointed but Relieved Face'],
    },
    {
     name: 'Thinking Face',
     short_names: ['thinking_face'],
     text: '',
     emoticons: [],
     keywords: ['Thinking Face'],
    },
    {
     name: 'Face Savouring Delicious Food',
     short_names: ['yum'],
     text: '',
     emoticons: [],
     keywords: ['Face Savouring Delicious Food'],
    },
    {
     name: 'Face with Stuck-out Tongue',
     short_names: ['stuck_out_tongue'],
     text: '',
     emoticons: [],
     keywords: ['Face with Stuck-out Tongue'],
    },
    {
     name: 'Face with Finger Covering Closed Lips',
     short_names: ['shushing_face', 'face_with_finger_covering_closed_lips'],
     text: '',
     emoticons: [],
     keywords: ['Face with Finger Covering Closed Lips'],
    },
    {
     name: 'Hugging Face',
     short_names: ['hugging_face'],
     text: '',
     emoticons: [],
     keywords: ['Hugging Face'],
    },
    {
     name: 'Smiling Face with Sunglasses',
     short_names: ['sunglasses'],
     text: '',
     emoticons: [],
     keywords: ['Smiling Face with Sunglasses'],
    },
    {
     name: 'Face with Party Horn and Party Hat',
     short_names: ['partying_face'],
     text: '',
     emoticons: [],
     keywords: ['Face with Party Horn and Party Hat'],
    }
]
